### PR TITLE
Repair import events & tab->space

### LINKED ISSUE #250: Features and events time line reports wrong number of events
According to the timeline report, there are a very large number of sigmoids in this half hour when there are not.

Screen Shot 2023-01-27 at 1 07 58 PM

The timeline is mischaracterizing the number of events.

This may be an API issue, or it may be a front end issue.

### PR DESCRIPTION
**Pull request by dgarciabriseno**
Fixes #250

### CODE REVIEW

File: src/Database/Statistics.php [hunk 1]
```diff
@@ -1653,12 +1653,16 @@ public function colourBrightness($hex, $percent) {
     public function updateDataCoverageOverRange($start, $end) {
```
Comment (dgarciabriseno) [inline src/Database/Statistics.php:1653]: This function has the relevant changes.

**Comment by dgarciabriseno** [comment]
Issue was that start and end dates were wrong so the 30m range was actually using a full day's range. Instead of showing counts for 30m it was showing the daily count.
