### PR TITLE
Don't allow movie requeue if movie is processing

### LINKED ISSUE #200: reQueueMovie with force=true should not requeue if the movie is being processed.
Testing with HvPy discovered this issue. The problem seems to be that when you force reQueue a movie while it's being built, the build processes crash into each other and cause the movie to fail.

### PR DESCRIPTION
**Pull request by dgarciabriseno**
Fixes #200

### CODE REVIEW

File: tests/unit_tests/movies/reQueueMovieTest.php [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+     * Marks the movie as complete in the database and invalidates the cache
+     */
+    private function _markMovieAsComplete(Movie_HelioviewerMovie $movie) {
+        $db = new Database_ImgIndex();
+        $success = $db->markMovieAsFinished($movie->id, "mp4", 5);
+        if (!$success) {
+            $this->fail("Failed to mark movie as complete");
+        }
+        $movie->DeleteFromCache($movie->publicId);
+    }
```
Comment (dgarciabriseno) [inline tests/unit_tests/movies/reQueueMovieTest.php:64]: This is unused, can remove
